services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel

  postgres:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    env_file:
      - env/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/laravel
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=0
    command: ["create-project", "laravel/laravel", "."]

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  pgdata:
